server:
  port: 4040
  session-timeout: 60
  servlet:
    context-path: /moban
mybatisPlus:
  mapperLocations: classpath:/com/dhlg/module/*/*/dao/xml/*.xml,classpath:/com/dhlg/module/*/*/*/dao/xml/*.xml
  typeAliasesPackage: com.dhlg.module.*.*.entity

spring:
  # 文件上传
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    name: db
    type: com.alibaba.druid.pool.DruidDataSource #表明使用Druid连接池
    username: root
#    password: zmy1022a.
    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/houtaisql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://47.94.8.32:3306/houtaisql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 500
    maxActive: 1000 #最大连接池数量
    initialSize: 10 #初始化时建立物理连接的个数
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat #,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: admin # 登录druid的账号
    druidPassword: 123456 # 登录druid的密码
  redis:
    host: 47.94.8.32
#    host: 127.0.0.1
    port: 6379
    password: hehe
    jedis:
      pool:
        max-idle: 500
        min-idle: 0
        max-active: 512
        max-wait: -1
    timeout: 600 # 单位秒
  #mq配置---start
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: false
    #信任所有的包
    packages:
      trust-all: true
  jms:
    pub-sub-domain: true
  #mq配置---end
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mail:
    host: smtp.qq.com
    default-encoding: utf-8
    username: 2740835057@qq.com
    password: wioqltexuiezdejc

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  mail:
#    from: 2740835057@qq.com
#    nickname: true
#    password: wioqltexuiezdejc
#    mailHost: smtp.qq.com
#    port: 587

shiro:
  # 加密算法
  algorithmName: "md5"
  # hash 次数
  hashIterations: 2


#showSql
logging:
  level:
    com:
      example:
        mapper : debug

common:
  password: 123456 #默认密码
  #默认头像
  headPortraitSrc: "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1600421306465&di=ceb5e70c7a4d5a7b55f7bcb1d1a9c8e3&imgtype=0&src=http%3A%2F%2Fa2.att.hudong.com%2F36%2F48%2F19300001357258133412489354717.jpg"
  #网络访问路径
  fileNetSrc: http://120.25.197.11/resources/
  #云服务器路径
#  fileDownSrc: /usr/local/resources/
  templateUrl: \src\main\resources\templates\
  dataBase: houtaisql
  fileDownSrc: D:/resource/

